#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://research.cs.wisc.edu/multifacet/papers/can11_gem5.pdf" "The-gem5-Simulator.pdf"
dl "https://arxiv.org/pdf/2007.03152" "The-gem5-Simulator-Version-20-0.pdf"
dl "http://hdl.handle.net/1721.1/90820" "ZSim-Fast-and-Accurate-Microarchitectural-Simula.pdf"
dl "https://escholarship.org/content/qt9bm2g3p7/qt9bm2g3p7.pdf" "Automatically-Characterizing-Large-Scale-Program.pdf"
echo "done -> $OUT/"
