#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://www.image-net.org/static_files/files/supervision.pdf" "ImageNet-Classification-with-Deep-Convolutional.pdf"
dl "https://arxiv.org/pdf/1409.1556" "Very-Deep-Convolutional-Networks-for-Large-Scale.pdf"
dl "https://arxiv.org/pdf/1506.01497" "Faster-R-CNN-Towards-Real-Time-Object-Detection.pdf"
dl "https://arxiv.org/pdf/1506.02640" "You-Only-Look-Once-YOLO.pdf"
dl "https://arxiv.org/pdf/1409.4842" "Going-Deeper-with-Convolutions-GoogLeNet-Incepti.pdf"
dl "https://arxiv.org/pdf/1411.4038" "Fully-Convolutional-Networks-for-Semantic-Segmen.pdf"
dl "https://arxiv.org/pdf/1505.04597" "U-Net-Convolutional-Networks-for-Biomedical-Imag.pdf"
dl "https://arxiv.org/pdf/1703.06870" "Mask-R-CNN.pdf"
dl "https://arxiv.org/pdf/1905.11946" "EfficientNet-Rethinking-Model-Scaling.pdf"
echo "done -> $OUT/"
