#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://www.dcs.gla.ac.uk/~wpc/grcs/kilburn.pdf" "One-Level-Storage-System-Atlas.pdf"
dl "https://home.engineering.iastate.edu/~zzhang/courses/cpre581-f05/reading/smith-csur82-cache.pdf" "Cache-Memories.pdf"
dl "https://people.eecs.berkeley.edu/~kubitron/courses/cs252-F03/handouts/papers/p195-kroft.pdf" "Lockup-Free-Instruction-Fetch-Prefetch-Cache-Org.pdf"
dl "http://bitsavers.trailing-edge.com/pdf/dec/tech_reports/WRL-TN-14.pdf" "Improving-Direct-Mapped-Cache-Performance-by-Add.pdf"
dl "https://safari.ethz.ch/architecture/fall2022/lib/exe/fetch.php?media=joseph_isca97.pdf" "Prefetching-Using-Markov-Predictors.pdf"
dl "https://www.jaleels.org/ajaleel/publications/isca2007-dip.pdf" "Adaptive-Insertion-Policies-for-High-Performance.pdf"
dl "https://www.jaleels.org/ajaleel/publications/isca2010-rrip.pdf" "High-Performance-Cache-Replacement-Using-Re-Refe.pdf"
dl "https://users.cs.utah.edu/~rajeev/cs7810/papers/kim02.pdf" "An-Adaptive-Non-Uniform-Cache-Structure-NUCA.pdf"
dl "https://www.cs.rice.edu/CS/Architecture/docs/rixner-isca00.pdf" "Memory-Access-Scheduling.pdf"
dl "https://people.inf.ethz.ch/omutlu/pub/parbs_isca08.pdf" "Parallelism-Aware-Batch-Scheduling.pdf"
dl "https://www.cs.cmu.edu/~18742/papers/Loh2008.pdf" "3D-Stacked-Memory-Architectures-for-Multi-Core-P.pdf"
dl "https://people.inf.ethz.ch/omutlu/pub/dram-row-hammer_isca14.pdf" "Flipping-Bits-in-Memory-Without-Accessing-Them-R.pdf"
dl "https://www.cs.rice.edu/CS/Architecture/docs/barr-isca10.pdf" "Translation-Caching-Skip-Don-t-Walk-the-Page-Tab.pdf"
dl "https://www.cs.cmu.edu/~garth/RAIDpaper/Patterson88.pdf" "A-Case-for-Redundant-Arrays-of-Inexpensive-Disks.pdf"
dl "https://web.stanford.edu/~ouster/cgi-bin/papers/lfs.pdf" "The-Design-and-Implementation-of-a-Log-Structure.pdf"
dl "https://www.usenix.org/legacy/events/usenix08/tech/full_papers/agrawal/agrawal.pdf" "Design-Tradeoffs-for-SSD-Performance.pdf"
dl "https://pdfs.semanticscholar.org/5016/c8c7f2795f9f6828edbedd0f1a587863ea6d.pdf" "DFTL-A-Flash-Translation-Layer-Employing-Demand.pdf"
dl "https://www.seas.upenn.edu/~leebcc/documents/lee2009-isca.pdf" "Architecting-Phase-Change-Memory-as-a-Scalable-D.pdf"
dl "https://www.sigops.org/s/conferences/sosp/2009/papers/condit-sosp09.pdf" "Better-I-O-Through-Byte-Addressable-Persistent-M.pdf"
dl "https://safari.ethz.ch/architecture/fall2021/lib/exe/fetch.php?media=isca09-disaggregate.pdf" "Disaggregated-Memory-for-Expansion-and-Sharing-i.pdf"
echo "done -> $OUT/"
