#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://www.cis.upenn.edu/~stevez/cis670/pdfs/pi-calculus.pdf" "A-Calculus-of-Mobile-Processes-I.pdf"
dl "http://rsim.cs.uiuc.edu/Pubs/popl05.pdf" "The-Java-Memory-Model.pdf"
dl "https://www.cl.cam.ac.uk/~pes20/cpp/popl085ap-sewell.pdf" "Mathematizing-C-Concurrency.pdf"
dl "https://lamport.azurewebsites.net/pubs/time-clocks.pdf" "Time-Clocks-and-the-Ordering-of-Events-in-a-Dist.pdf"
dl "https://www.cl.cam.ac.uk/~pes20/weakmemory/cacm.pdf" "x86-TSO-A-Rigorous-and-Usable-Programmer-s-Model.pdf"
dl "https://people.mpi-sws.org/~dreyer/papers/promising/paper.pdf" "A-Promising-Semantics-for-Relaxed-Memory-Concurr.pdf"
echo "done -> $OUT/"
