#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://www.cs.toronto.edu/~hinton/absps/naturebp.pdf" "Learning-representations-by-back-propagating-err.pdf"
dl "https://papers.nips.cc/paper_files/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html" "ImageNet-Classification-with-Deep-Convolutional.pdf"
dl "https://proceedings.neurips.cc/paper_files/paper/2012/file/c399862d3b9d6b76c8436e924a68c45b-Paper.pdf" "ImageNet-Classification-with-Deep-Convolutional.pdf"
dl "https://arxiv.org/pdf/1512.03385" "Deep-Residual-Learning-for-Image-Recognition-Res.pdf"
dl "https://deeplearning.cs.cmu.edu/F23/document/readings/LSTM.pdf" "Long-Short-Term-Memory.pdf"
dl "https://arxiv.org/abs/1301.3781" "Efficient-Estimation-of-Word-Representations-in.pdf"
dl "https://arxiv.org/pdf/1301.3781" "Efficient-Estimation-of-Word-Representations-in.pdf"
dl "https://arxiv.org/abs/1706.03762" "Attention-Is-All-You-Need.pdf"
dl "https://arxiv.org/pdf/1706.03762" "Attention-Is-All-You-Need.pdf"
dl "https://arxiv.org/abs/1406.2661" "Generative-Adversarial-Nets-GAN.pdf"
dl "https://arxiv.org/pdf/1406.2661" "Generative-Adversarial-Nets-GAN.pdf"
dl "https://arxiv.org/abs/2006.11239" "Denoising-Diffusion-Probabilistic-Models-DDPM.pdf"
dl "https://arxiv.org/pdf/2006.11239" "Denoising-Diffusion-Probabilistic-Models-DDPM.pdf"
dl "https://web.stanford.edu/class/psych209/Readings/MnihEtAlHassibis15NatureControlDeepRL.pdf" "Human-level-Control-through-Deep-Reinforcement-L.pdf"
dl "https://storage.googleapis.com/deepmind-media/alphago/AlphaGoNaturePaper.pdf" "Mastering-the-Game-of-Go-with-Deep-Neural-Networ.pdf"
dl "https://arxiv.org/abs/2001.08361" "Scaling-Laws-for-Neural-Language-Models.pdf"
dl "https://arxiv.org/pdf/2001.08361" "Scaling-Laws-for-Neural-Language-Models.pdf"
dl "https://arxiv.org/abs/2210.03629" "ReAct-Synergizing-Reasoning-and-Acting-in-Langua.pdf"
dl "https://arxiv.org/pdf/2210.03629" "ReAct-Synergizing-Reasoning-and-Acting-in-Langua.pdf"
echo "done -> $OUT/"
