#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://calhoun.nps.edu/server/api/core/bitstreams/54e90734-ceb5-4f4f-94f6-83e51cd2da73/content" "A-Unified-Approach-to-Global-Program-Optimizatio.pdf"
dl "https://www.cs.utexas.edu/~pingali/CS380C/2010/papers/ssaCytron.pdf" "Efficiently-Computing-Static-Single-Assignment-F.pdf"
dl "https://www.cs.utexas.edu/~pingali/CS380C/2010/papers/p291-wegman.pdf" "Constant-Propagation-with-Conditional-Branches-S.pdf"
dl "https://www.lighterra.com/papers/valuerangeprop/Patterson1995-ValueRangeProp.pdf" "Accurate-Static-Branch-Prediction-by-Value-Range.pdf"
dl "https://www.cs.tufts.edu/~nr/cs257/archive/keith-cooper/value-numbering.pdf" "Value-Numbering.pdf"
dl "http://rsim.cs.uiuc.edu/arch/qual_papers/compilers/knoop92.pdf" "Lazy-Code-Motion.pdf"
dl "https://link.springer.com/content/pdf/10.1007/978-3-540-24723-4_12.pdf" "Value-Based-Partial-Redundancy-Elimination.pdf"
dl "https://www.cs.rice.edu/~keith/Publications/OSR.pdf" "Operator-Strength-Reduction.pdf"
dl "https://link.springer.com/content/pdf/10.1007/BFb0026428.pdf" "Strength-Reduction-via-SSAPRE.pdf"
dl "https://dspace.mit.edu/bitstream/handle/1721.1/5753/AIM-443.pdf" "Debunking-the-Expensive-Procedure-Call-Myth.pdf"
dl "https://www.itu.dk/people/sestoft/pebook/" "Partial-Evaluation-and-Automatic-Program-Generat.pdf"
echo "done -> $OUT/"
