#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://calhoun.nps.edu/server/api/core/bitstreams/54e90734-ceb5-4f4f-94f6-83e51cd2da73/content" "A-Unified-Approach-to-Global-Program-Optimizatio.pdf"
dl "https://www.di.ens.fr/~cousot/publications.www/CousotCousot-POPL-77-ACM-p238--252-1977.pdf" "Abstract-Interpretation-A-Unified-Lattice-Model.pdf"
dl "https://web.eecs.umich.edu/~mahlke/courses/583f23/reading/cytron_toplas_91.pdf" "Efficiently-Computing-Static-Single-Assignment-F.pdf"
dl "https://www.cs.cornell.edu/courses/cs711/2005fa/papers/steensgaard-popl96.pdf" "Points-to-Analysis-in-Almost-Linear-Time.pdf"
dl "http://rsim.cs.uiuc.edu/arch/qual_papers/compilers/knoop92.pdf" "Lazy-Code-Motion.pdf"
dl "https://web.eecs.umich.edu/~mahlke/courses/583f12/reading/chaitin82.pdf" "Register-Allocation-Spilling-via-Graph-Coloring.pdf"
dl "http://rsim.cs.uiuc.edu/arch/qual_papers/compilers/allen87.pdf" "Automatic-Translation-of-FORTRAN-Programs-to-Vec.pdf"
dl "https://www.ece.lsu.edu/jxr/Publications-pdf/pldi08.pdf" "A-Practical-Automatic-Polyhedral-Parallelizer-an.pdf"
dl "https://llvm.org/pubs/2004-01-30-CGO-LLVM.pdf" "LLVM-A-Compilation-Framework-for-Lifelong-Progra.pdf"
dl "https://arxiv.org/pdf/2002.11054" "MLIR-Scaling-Compiler-Infrastructure-for-Domain.pdf"
dl "https://xavierleroy.org/publi/compcert-CACM.pdf" "Formal-Verification-of-a-Realistic-Compiler-Comp.pdf"
dl "https://users.cs.utah.edu/~regehr/papers/pldi15.pdf" "Provably-Correct-Peephole-Optimizations-with-Ali.pdf"
echo "done -> $OUT/"
