#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://arxiv.org/pdf/1503.02531" "Distilling-the-Knowledge-in-a-Neural-Network.pdf"
dl "https://arxiv.org/pdf/2001.08361" "Scaling-Laws-for-Neural-Language-Models.pdf"
dl "https://arxiv.org/pdf/2203.15556" "Training-Compute-Optimal-Large-Language-Models-C.pdf"
echo "done -> $OUT/"
