#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://arxiv.org/pdf/1503.02531" "Distilling-the-Knowledge-in-a-Neural-Network.pdf"
dl "https://arxiv.org/pdf/2001.08361" "Scaling-Laws-for-Neural-Language-Models.pdf"
dl "https://arxiv.org/pdf/2203.15556" "Training-Compute-Optimal-Large-Language-Models-C.pdf"
dl "https://arxiv.org/pdf/1710.03740" "Mixed-Precision-Training.pdf"
dl "https://arxiv.org/pdf/1711.05101" "Decoupled-Weight-Decay-Regularization-AdamW.pdf"
dl "https://arxiv.org/pdf/1608.03983" "SGDR-Warm-Restarts.pdf"
dl "https://arxiv.org/pdf/1706.03741" "Deep-RL-from-Human-Preferences.pdf"
dl "https://arxiv.org/pdf/2203.02155" "Training-Language-Models-to-Follow-Instructions.pdf"
dl "https://arxiv.org/pdf/2106.09685" "LoRA-Low-Rank-Adaptation-of-Large-Language-Model.pdf"
dl "https://arxiv.org/pdf/2206.07682" "Emergent-Abilities-of-Large-Language-Models.pdf"
echo "done -> $OUT/"
