#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://www.cs.cmu.edu/afs/cs/academic/class/15869-f11/www/readings/lindholm08_tesla.pdf" "NVIDIA-Tesla-A-Unified-Graphics-and-Computing-Ar.pdf"
dl "https://arxiv.org/pdf/1704.04760" "In-Datacenter-Performance-Analysis-of-a-Tensor-P.pdf"
dl "https://cs.brown.edu/courses/csci2950-u/s18/papers/barroso09warehouse.pdf" "The-Datacenter-as-a-Computer.pdf"
echo "done -> $OUT/"
