#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://web.archive.org/web/20191029093307id_/http://www-inst.eecs.berkeley.edu/~n252/paper/Amdahl.pdf" "Validity-of-the-Single-Processor-Approach-to-Ach.pdf"
dl "https://escholarship.org/content/qt78h8v7mr/qt78h8v7mr.pdf" "Roofline-An-Insightful-Visual-Performance-Model.pdf"
dl "https://www.cs.virginia.edu/~evans/greatworks/tomasulo.pdf" "An-Efficient-Algorithm-for-Exploiting-Multiple-A.pdf"
dl "https://www.ece.ucdavis.edu/~akella/270W05/mcfarling93combining.pdf" "Combining-Branch-Predictors.pdf"
dl "https://home.engineering.iastate.edu/~zzhang/courses/cpre581-f05/reading/smith-csur82-cache.pdf" "Cache-Memories.pdf"
dl "https://lamport.azurewebsites.net/pubs/multi.pdf" "How-to-Make-a-Multiprocessor-Computer-That-Corre.pdf"
dl "https://arxiv.org/pdf/1704.04760" "In-Datacenter-Performance-Analysis-of-a-Tensor-P.pdf"
dl "https://static.googleusercontent.com/media/research.google.com/en//archive/googlecluster-ieee.pdf" "Web-Search-for-a-Planet-The-Google-Cluster-Archi.pdf"
dl "https://research.cs.wisc.edu/multifacet/papers/can11_gem5.pdf" "The-gem5-Simulator.pdf"
dl "https://arxiv.org/pdf/1801.01203" "Spectre-Attacks-Exploiting-Speculative-Execution.pdf"
dl "https://people.eecs.berkeley.edu/~kubitron/courses/cs252-S09/handouts/papers/p263-fisher.pdf" "Very-Long-Instruction-Word-Architectures-and-the.pdf"
dl "https://people.eecs.berkeley.edu/~culler/courses/cs252-s05/papers/amdahl.pdf" "Architecture-of-the-IBM-System-360.pdf"
echo "done -> $OUT/"
