#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://people.eecs.berkeley.edu/~culler/courses/cs252-s05/papers/amdahl.pdf" "Architecture-of-the-IBM-System-360.pdf"
dl "https://www.cs.princeton.edu/courses/archive/fall09/cos375/Kilburn.pdf" "One-Level-Storage-System.pdf"
dl "https://www.andrew.cmu.edu/course/15-440/assets/READINGS/liptay1968.pdf" "Structural-Aspects-of-the-System-360-Model-85-II.pdf"
dl "https://cs.uwaterloo.ca/~mashti/cs850-f18/papers/cdc6600.pdf" "Parallel-Operation-in-the-Control-Data-6600.pdf"
dl "http://bitsavers.org/pdf/ibm/IBM_Journal_of_Research_and_Development/111/ibmrd1101C.pdf" "The-IBM-System-360-Model-91-Machine-Philosophy-a.pdf"
dl "https://refs.devinmcgloin.com/worrydream/Barton%20-%20A%20New%20Approach%20to%20the%20Functional%20Design%20of%20a%20New%20Computer.pdf" "A-New-Approach-to-the-Functional-Design-of-a-Dig.pdf"
dl "https://cray-history.net/wp-content/uploads/2021/07/cray1_PaperbyRussell.pdf" "The-CRAY-1-Computer-System.pdf"
dl "https://archive.computerhistory.org/resources/text/DEC/pdp-11/dec.pdp-11.a_new_architecture_for_mini-computers-the_dec_pdp-11.1970.102630380.pdf" "A-New-Architecture-for-Minicomputers-The-DEC-PDP.pdf"
dl "https://tcm.computerhistory.org/ComputerTimeline/Chap42_vax11-780_CS2.pdf" "VAX-11-780-A-Virtual-Address-Extension-to-the-DE.pdf"
dl "https://courses.grainger.illinois.edu/ece511/fa2005/papers/Radin.1982.ASPLOS.pdf" "The-801-Minicomputer.pdf"
dl "http://people.duke.edu/~bcl15/teachdir/ece252_fall11/Hennessy.pdf" "MIPS-A-Microprocessor-Architecture.pdf"
dl "http://bitsavers.org/pdf/ibm/IBM_Journal_of_Research_and_Development/341/ibmrd3401E.pdf" "IBM-RISC-System-6000-Processor-Architecture.pdf"
dl "https://www2.eecs.berkeley.edu/Pubs/TechRpts/2014/EECS-2014-146.pdf" "Instruction-Sets-Should-Be-Free-The-Case-for-RIS.pdf"
dl "https://baltazarstudios.com/webshare/A-Z80/Library/The%20History%20of%204004.pdf" "The-History-of-the-4004.pdf"
dl "https://cse.ucdenver.edu/~gita/csprojects/CSC5593/Organization/Papers/keltcher-opteron.pdf" "The-AMD-Opteron-Processor-for-Multiprocessor-Ser.pdf"
dl "https://pages.cs.wisc.edu/~markhill/restricted/ieeemicro2000_ia64isa.pdf" "Introducing-the-IA-64-Architecture.pdf"
dl "https://people.eecs.berkeley.edu/~kubitron/courses/cs252-S10/handouts/papers/alpha-ieee.pdf" "The-Alpha-21264-Microprocessor.pdf"
echo "done -> $OUT/"
