#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://www.cs.toronto.edu/~hinton/absps/science.pdf" "Reducing-the-Dimensionality-of-Data-with-Neural.pdf"
dl "https://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf" "Understanding-the-difficulty-of-training-deep-fe.pdf"
dl "https://jmlr.org/papers/volume15/srivastava14a/srivastava14a.pdf" "Dropout-A-Simple-Way-to-Prevent-Neural-Networks.pdf"
dl "https://arxiv.org/pdf/1502.03167" "Batch-Normalization.pdf"
dl "https://arxiv.org/pdf/1412.6980" "Adam-A-Method-for-Stochastic-Optimization.pdf"
dl "https://arxiv.org/pdf/1512.03385" "Deep-Residual-Learning-for-Image-Recognition.pdf"
echo "done -> $OUT/"
