#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://homepages.inf.ed.ac.uk/wadler/papers/papers-we-love/milner-type-polymorphism.pdf" "A-Theory-of-Type-Polymorphism-in-Programming.pdf"
dl "https://steshaw.org/hm/milner-damas.pdf" "Principal-Type-Schemes-for-Functional-Programs.pdf"
dl "http://lucacardelli.name/Papers/BasicTypechecking.pdf" "Basic-Polymorphic-Typechecking.pdf"
dl "http://girard.perso.math.cnrs.fr/These.pdf" "Interpr-tation-fonctionnelle-et-limination-des-c.pdf"
dl "https://www.cis.upenn.edu/~stevez/cis670/pdfs/Reynolds74.pdf" "Towards-a-Theory-of-Type-Structure.pdf"
dl "https://www.cs.cmu.edu/~crary/819-f09/Reynolds83.pdf" "Types-Abstraction-and-Parametric-Polymorphism.pdf"
dl "https://people.mpi-sws.org/~dreyer/tor/papers/wadler.pdf" "Theorems-for-Free.pdf"
dl "http://lucacardelli.name/Papers/OnUnderstanding.A4.pdf" "On-Understanding-Types-Data-Abstraction-and-Poly.pdf"
dl "https://theory.stanford.edu/~jcm/papers/mitch-plotkin-88.pdf" "Abstract-Types-Have-Existential-Type.pdf"
dl "https://people.csail.mit.edu/dnj/teaching/6898/papers/wadler88.pdf" "How-to-Make-ad-hoc-Polymorphism-Less-ad-hoc.pdf"
dl "https://web.cecs.pdx.edu/~mpj/pubs/fpca93.pdf" "A-System-of-Constructor-Classes.pdf"
dl "https://www.cs.utexas.edu/~wcook/papers/FBound89/CookFBound89.pdf" "F-Bounded-Polymorphism-for-Object-Oriented-Progr.pdf"
dl "http://lucacardelli.name/Papers/FSub.A4.pdf" "An-Extension-of-System-F-with-Subtyping-F-sub.pdf"
dl "https://www.cs.cmu.edu/~crary/819-f09/Howard80.pdf" "The-Formulae-as-Types-Notion-of-Construction.pdf"
dl "https://raw.githubusercontent.com/michaelt/martin-lof/master/pdfs/Bibliopolis-Book-retypeset-1984.pdf" "Intuitionistic-Type-Theory.pdf"
dl "https://publikationen.bibliothek.kit.edu/44298/776748" "Putting-Type-Annotations-to-Work.pdf"
dl "https://www.cis.upenn.edu/~bcpierce/papers/lti-toplas.pdf" "Local-Type-Inference.pdf"
dl "https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/putting.pdf" "Practical-Type-Inference-for-Arbitrary-Rank-Type.pdf"
dl "https://arxiv.org/pdf/1306.6032" "Complete-and-Easy-Bidirectional-Typechecking-for.pdf"
dl "https://simon.peytonjones.org/assets/pdfs/outsideinx.pdf" "OutsideIn-X-Modular-Type-Inference-with-Local-As.pdf"
echo "done -> $OUT/"
