#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://www.cis.upenn.edu/~stevez/cis670/pdfs/Reynolds74.pdf" "Towards-a-Theory-of-Type-Structure.pdf"
dl "https://research.cs.queensu.ca/home/cordy/cisc860/Biblio/hurd/misc/milner78.pdf" "A-Theory-of-Type-Polymorphism-in-Programming.pdf"
dl "https://courses.cs.washington.edu/courses/cse503/10wi/readings/p207-damas.pdf" "Principal-Type-Schemes-for-Functional-Programs.pdf"
dl "https://lucacardelli.name/papers/onunderstanding.a4.pdf" "On-Understanding-Types-Data-Abstraction-and-Poly.pdf"
echo "done -> $OUT/"
