#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://plv.mpi-sws.org/plerg/papers/comprehending-monads.pdf" "Comprehending-Monads.pdf"
echo "done -> $OUT/"
