#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://plv.mpi-sws.org/plerg/papers/comprehending-monads.pdf" "Comprehending-Monads.pdf"
dl "https://www.st.cs.uni-saarland.de/edu/seminare/2005/advanced-fp/docs/wadler-essence-fp.pdf" "The-Essence-of-Functional-Programming.pdf"
dl "https://homepages.inf.ed.ac.uk/wadler/papers/marktoberdorf/baastad.pdf" "Monads-for-functional-programming.pdf"
dl "https://person.dibris.unige.it/moggi-eugenio/ftp/ic91.pdf" "Notions-of-Computation-and-Monads.pdf"
dl "https://www.microsoft.com/en-us/research/wp-content/uploads/1993/01/imperative.pdf" "Imperative-Functional-Programming.pdf"
dl "https://web.engr.oregonstate.edu/~walkiner/teaching/cs583-sp21/files/Liang-MonadTransformers.pdf" "Monad-Transformers-and-Modular-Interpreters.pdf"
dl "https://www.staff.city.ac.uk/~ross/papers/Applicative.pdf" "Applicative-Programming-with-Effects.pdf"
dl "https://www.cse.chalmers.se/~rjmh/Papers/arrows.pdf" "Generalising-Monads-to-Arrows.pdf"
dl "https://homepages.inf.ed.ac.uk/gdp/publications/alg_ops_gen_effects.pdf" "Algebraic-Operations-and-Generic-Effects.pdf"
dl "https://homepages.inf.ed.ac.uk/gdp/publications/Effect_Handlers.pdf" "Handlers-of-Algebraic-Effects.pdf"
dl "https://arxiv.org/pdf/1203.1539" "Programming-with-Algebraic-Effects-and-Handlers.pdf"
dl "https://arxiv.org/pdf/1406.2061" "Koka-Programming-with-Row-Polymorphic-Effect-Typ.pdf"
dl "https://webspace.science.uu.nl/~swier004/publications/2008-jfp.pdf" "Data-Types-la-Carte.pdf"
dl "https://okmij.org/ftp/Haskell/extensible/exteff.pdf" "Extensible-Effects-An-Alternative-to-Monad-Trans.pdf"
echo "done -> $OUT/"
