#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://calhoun.nps.edu/server/api/core/bitstreams/54e90734-ceb5-4f4f-94f6-83e51cd2da73/content" "A-Unified-Approach-to-Global-Program-Optimizatio.pdf"
dl "https://www.di.ens.fr/~cousot/COUSOTpapers/publications.www/CousotCousot-POPL-77-ACM-p238--252-1977.pdf" "Abstract-Interpretation-A-Unified-Lattice-Model.pdf"
dl "https://research.cs.wisc.edu/wpis/papers/popl95.pdf" "Precise-Interprocedural-Dataflow-Analysis-via-Gr.pdf"
dl "https://amturing.acm.org/p137-allen.pdf" "A-Program-Data-Flow-Analysis-Procedure.pdf"
dl "https://c9x.me/compile/bib/quickdom.pdf" "A-Simple-Fast-Dominance-Algorithm.pdf"
dl "https://web.eecs.umich.edu/~mahlke/courses/583f23/reading/cytron_toplas_91.pdf" "Efficiently-Computing-SSA-Form-and-the-Control-D.pdf"
dl "https://c9x.me/compile/bib/braun13cc.pdf" "Simple-and-Efficient-Construction-of-Static-Sing.pdf"
dl "https://c9x.me/compile/bib/constpropssa.pdf" "Constant-Propagation-with-Conditional-Branches-S.pdf"
dl "https://c9x.me/compile/bib/click-gvn.pdf" "Global-Code-Motion-Global-Value-Numbering.pdf"
dl "https://web.eecs.umich.edu/~mahlke/courses/583f23/reading/ferrante_toplas_87.pdf" "The-Program-Dependence-Graph-and-Its-Use-in-Opti.pdf"
dl "https://www.oracle.com/technetwork/java/javase/tech/c2-ir95-150110.pdf" "A-Simple-Graph-Based-Intermediate-Representation.pdf"
dl "https://www.usenix.org/legacy/events/jvm01/full_papers/paleczny/paleczny.pdf" "The-Java-HotSpot-Server-Compiler.pdf"
dl "https://llvm.org/pubs/2004-01-30-CGO-LLVM.pdf" "LLVM-A-Compilation-Framework-for-Lifelong-Progra.pdf"
dl "https://rosstate.org/publications/eqsat/eqsat_tate_popl09.pdf" "Equality-Saturation-A-New-Approach-to-Optimizati.pdf"
dl "https://arxiv.org/pdf/2002.11054" "MLIR-Scaling-Compiler-Infrastructure-for-Domain.pdf"
echo "done -> $OUT/"
