#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://llvm.org/pubs/2004-01-30-CGO-LLVM.pdf" "LLVM-A-Compilation-Framework-for-Lifelong-Progra.pdf"
dl "https://www.ece.lsu.edu/jxr/Publications-pdf/pldi08.pdf" "A-Practical-Automatic-Polyhedral-Parallelizer-an.pdf"
dl "https://people.csail.mit.edu/jrk/halide-pldi13.pdf" "Halide-A-Language-and-Compiler-for-Optimizing-Pa.pdf"
dl "https://arxiv.org/pdf/1802.04799" "TVM-An-Automated-End-to-End-Optimizing-Compiler.pdf"
dl "https://arxiv.org/pdf/2002.11054" "MLIR-Scaling-Compiler-Infrastructure-for-Domain.pdf"
dl "https://arxiv.org/pdf/1807.06735" "BOLT-A-Practical-Binary-Optimizer-for-Data-Cente.pdf"
echo "done -> $OUT/"
