#!/usr/bin/env python3
"""Generate a subtopic's reading-guide.html (+ fetch.sh) from its README.md.

The README is the source of truth: an `# H1` title, an intro paragraph, and a
bulleted paper list in the house format

    - **Title** — Authors, Year, Venue. Why-sentence. [DOI](url) · [PDF](url)

This emits a printable reading-guide.html in the shared house style (linking the
repo's lib/guide.css) and a fetch.sh that downloads the [PDF]-labelled links.
Year/era tags like *foundational.* are stripped (no era sections — see CLAUDE.md).

Usage: lib/gen-guide.py <subtopic-dir> [<css-relative-path>]
"""
import os, re, sys

d = sys.argv[1].rstrip("/")
css = sys.argv[2] if len(sys.argv) > 2 else "../../lib/guide.css"
readme = os.path.join(d, "README.md")
text = open(readme, encoding="utf-8").read()

title = "Reading list"
lead = ""
for line in text.splitlines():
    m = re.match(r"#\s+(.+)", line)
    if m:
        title = m.group(1).strip()
        break
# first non-heading, non-bullet paragraph = lead (accumulate until a blank line)
lead_lines = []
for line in text.splitlines():
    s = line.strip()
    if not lead_lines:
        if s and not s.startswith("#") and not s.startswith("- ") and not s.startswith("*"):
            lead_lines.append(s)
    else:
        if not s or s.startswith("- ") or s.startswith("#"):
            break
        lead_lines.append(s)
lead = " ".join(lead_lines)

LINK = re.compile(r"\[([^\]]+)\]\((https?://[^)]+)\)")
ERA = re.compile(r"\*(foundational|post-?2002|modern|pre-?2002)\.?\*", re.I)

def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

papers, pdfs = [], []
for line in text.splitlines():
    m = re.match(r"-\s+\*\*(.+?)\*\*\s*(.*)$", line)
    if not m:
        continue
    ptitle, rest = m.group(1), m.group(2)
    links = LINK.findall(rest)
    body = LINK.sub("", rest)
    body = ERA.sub("", body)
    body = body.lstrip("—- ").strip()
    body = re.sub(r"\s*·\s*$", "", body).strip()
    body = re.sub(r"\s{2,}", " ", body)
    has_pdf = any(lbl.lower() in ("pdf", "page") for lbl, _ in links)
    badge = ('<span class="badge b-pdf">PDF</span>' if has_pdf
             else '<span class="badge b-web">DOI</span>')
    anchors = " &middot; ".join(f'<a href="{u}">{esc(lbl)}</a>' for lbl, u in links)
    papers.append((ptitle, body, badge, anchors))
    for lbl, u in links:
        if lbl.lower() == "pdf":
            pdfs.append((ptitle, u))

lis = []
for ptitle, body, badge, anchors in papers:
    lis.append(
        f'  <li>\n'
        f'    <span class="title">{esc(ptitle)}</span>\n'
        f'    <div class="meta">{badge}{anchors}</div>\n'
        f'    <div class="why-here">{esc(body)}</div>\n'
        f'  </li>'
    )

html = (
    '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
    f'<title>{esc(title)}</title>\n<link rel="stylesheet" href="{css}">\n'
    '</head>\n<body>\n\n'
    f'<h1>{esc(title)}</h1>\n'
    + (f'<p class="sub">{esc(lead)}</p>\n' if lead else "")
    + '<p class="tally">In-depth landmark list for this subtopic. '
      '<span class="badge b-pdf">PDF</span>open copy available &middot; '
      '<span class="badge b-web">DOI</span>publisher link only.</p>\n\n'
    '<ol class="papers">\n' + "\n".join(lis) + "\n</ol>\n\n"
    "</body>\n</html>\n"
)
open(os.path.join(d, "reading-guide.html"), "w", encoding="utf-8").write(html)

# fetch.sh for the open PDFs
lines = ['#!/usr/bin/env bash',
         '# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.',
         'set -uo pipefail', 'cd "$(dirname "$0")"', 'OUT=pdfs; mkdir -p "$OUT"',
         'UA=\'Mozilla/5.0\'',
         'dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }']
def slug(t):
    return re.sub(r"[^A-Za-z0-9]+", "-", t)[:48].strip("-") + ".pdf"
for ptitle, u in pdfs:
    lines.append(f'dl "{u}" "{slug(ptitle)}"')
lines.append('echo "done -> $OUT/"')
fp = os.path.join(d, "fetch.sh")
open(fp, "w", encoding="utf-8").write("\n".join(lines) + "\n")
os.chmod(fp, 0o755)
print(f"{d}: {len(papers)} papers, {len(pdfs)} open PDFs")
