#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://www.cs.cmu.edu/~crary/819-f09/Landin66.pdf" "The-Next-700-Programming-Languages.pdf"
dl "https://www.cs.cmu.edu/~crary/819-f09/Hoare69.pdf" "An-Axiomatic-Basis-for-Computer-Programming.pdf"
dl "https://www.di.ens.fr/~cousot/publications.www/CousotCousot-POPL-77-ACM-p238--252-1977.pdf" "Abstract-Interpretation-A-Unified-Lattice-Model.pdf"
dl "https://www.cis.upenn.edu/~stevez/cis670/pdfs/Reynolds74.pdf" "Towards-a-Theory-of-Type-Structure.pdf"
dl "https://homepages.inf.ed.ac.uk/wadler/papers/papers-we-love/milner-type-polymorphism.pdf" "A-Theory-of-Type-Polymorphism-in-Programming.pdf"
dl "https://plv.mpi-sws.org/plerg/papers/comprehending-monads.pdf" "Comprehending-Monads.pdf"
dl "https://www.cs.cmu.edu/~jcr/seplogic.pdf" "Separation-Logic-A-Logic-for-Shared-Mutable-Data.pdf"
dl "http://rsim.cs.uiuc.edu/Pubs/popl05.pdf" "The-Java-Memory-Model.pdf"
dl "https://www.cl.cam.ac.uk/~pes20/cpp/popl085ap-sewell.pdf" "Mathematizing-C-Concurrency.pdf"
dl "http://scheme2006.cs.uchicago.edu/13-siek.pdf" "Gradual-Typing-for-Functional-Languages.pdf"
dl "https://plsyssec.github.io/cse227-spring25/papers/sel4.pdf" "seL4-Formal-Verification-of-an-OS-Kernel.pdf"
dl "https://plv.mpi-sws.org/rustbelt/popl18/paper.pdf" "RustBelt-Securing-the-Foundations-of-the-Rust-Pr.pdf"
echo "done -> $OUT/"
