#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://plsyssec.github.io/cse227-spring25/papers/sel4.pdf" "seL4-Formal-Verification-of-an-OS-Kernel.pdf"
dl "https://xavierleroy.org/publi/compcert-CACM.pdf" "Formal-Verification-of-a-Realistic-Compiler-Comp.pdf"
dl "https://plv.mpi-sws.org/rustbelt/popl18/paper.pdf" "RustBelt-Securing-the-Foundations-of-the-Rust-Pr.pdf"
echo "done -> $OUT/"
