#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://www.di.ens.fr/~cousot/publications.www/CousotCousot-POPL-77-ACM-p238--252-1977.pdf" "Abstract-Interpretation-A-Unified-Lattice-Model.pdf"
dl "https://www.di.ens.fr/~cousot/publications.www/CousotHalbwachs-POPL-78-ACM-p84--97-1978.pdf" "Automatic-Discovery-of-Linear-Restraints-Among-V.pdf"
dl "https://pcousot.github.io/publications/CousotCousot-POPL-79-ACM-p269--282-1979.pdf" "Systematic-Design-of-Program-Analysis-Frameworks.pdf"
dl "https://pcousot.github.io/publications/CousotCousot-PLILP-92-LNCS-n631-p269--295-1992.pdf" "Comparing-the-Galois-Connection-and-Widening-Nar.pdf"
dl "https://research.cs.wisc.edu/wpis/papers/popl95.pdf" "Precise-Interprocedural-Dataflow-Analysis-via-Gr.pdf"
dl "https://research.cs.wisc.edu/wpis/papers/toplas98a.pdf" "Solving-Shape-Analysis-Problems-in-Languages-wit.pdf"
dl "https://research.cs.wisc.edu/wpis/papers/toplas02.pdf" "Parametric-Shape-Analysis-via-3-Valued-Logic-TVL.pdf"
dl "https://pcousot.github.io/publications/BlanchetCousotEtAl-PLDI03-USletter.pdf" "A-Static-Analyzer-for-Large-Safety-Critical-Soft.pdf"
echo "done -> $OUT/"
