#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=b7efe971a34a0f2482e0b2520ffb31062dcdde62" "Program-Analysis-and-Specialization-for-the-C-Pr.pdf"
dl "https://www.cs.cornell.edu/courses/cs711/2005fa/papers/steensgaard-popl96.pdf" "Points-to-Analysis-in-Almost-Linear-Time.pdf"
dl "http://web.cs.ucla.edu/~palsberg/course/purdue/cs661/F01/papers/das-pldi00.pdf" "Unification-Based-Pointer-Analysis-with-Directio.pdf"
dl "http://web.cs.ucla.edu/~palsberg/course/purdue/cs661/F01/papers/heintze-tardieu-pldi01.pdf" "Ultra-fast-Aliasing-Analysis-using-CLA-a-million.pdf"
dl "https://www.cs.cornell.edu/courses/cs711/2005fa/papers/hind-paste01.pdf" "Pointer-Analysis-Haven-t-We-Solved-This-Problem.pdf"
dl "https://suif.stanford.edu/papers/pldi04.pdf" "Cloning-Based-Context-Sensitive-Pointer-Alias-An.pdf"
dl "https://www2.eecs.berkeley.edu/Pubs/TechRpts/2006/EECS-2006-31.pdf" "Refinement-Based-Context-Sensitive-Points-to-Ana.pdf"
dl "https://www.cs.utexas.edu/~lin/papers/pldi07.pdf" "The-Ant-and-the-Grasshopper-Fast-and-Accurate-Po.pdf"
echo "done -> $OUT/"
