#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://scheme2006.cs.uchicago.edu/13-siek.pdf" "Gradual-Typing-for-Functional-Languages.pdf"
dl "https://users.cs.northwestern.edu/~robby/pubs/papers/esop2009-wf.pdf" "Well-Typed-Programs-Can-t-Be-Blamed.pdf"
dl "https://goto.ucsd.edu/~rjhala/liquid/liquid_types_techrep.pdf" "Liquid-Types.pdf"
dl "https://arxiv.org/pdf/1710.09756" "Linear-Haskell.pdf"
dl "https://www.cis.upenn.edu/~bcpierce/courses/552-2008/resources/icfp-quickcheck.pdf" "QuickCheck-A-Lightweight-Tool-for-Random-Testing.pdf"
echo "done -> $OUT/"
