#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://www.cs.cmu.edu/~crary/819-f09/Landin66.pdf" "The-Next-700-Programming-Languages.pdf"
dl "https://homepages.inf.ed.ac.uk/gdp/publications/sos_jlap.pdf" "A-Structural-Approach-to-Operational-Semantics.pdf"
dl "https://www.di.ens.fr/~cousot/publications.www/CousotCousot-POPL-77-ACM-p238--252-1977.pdf" "Abstract-Interpretation.pdf"
echo "done -> $OUT/"
