#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "http://people.eecs.berkeley.edu/~kubitron/courses/cs252-S11/handouts/papers/barton.pdf" "A-New-Approach-to-the-Functional-Design-of-a-Dig.pdf"
dl "http://bitsavers.org/pdf/mit/ai/aim/AIM-514.pdf" "Design-of-a-LISP-based-microprocessor.pdf"
dl "https://web.archive.org/web/20070128024415id_/http://courses.ece.uiuc.edu/ece512/Papers/Dennis.1975.ISCA.pdf" "A-Preliminary-Architecture-for-a-Basic-Data-Flow.pdf"
dl "https://csg.csail.mit.edu/pubs/memos/Memo-271/Memo-271.pdf" "Executing-a-Program-on-the-MIT-Tagged-Token-Data.pdf"
dl "https://web.archive.org/web/20150114024834id_/http://www.ece.cmu.edu/~ece447/s14/lib/exe/fetch.php?media=p34-gurd.pdf" "The-Manchester-Prototype-Dataflow-Computer.pdf"
dl "https://people.eecs.berkeley.edu/~culler/courses/cs252-s05/papers/p398-papadopoulos.pdf" "Monsoon-An-Explicit-Token-Store-Architecture.pdf"
dl "https://people.eecs.berkeley.edu/~kubitron/courses/cs252-S09/handouts/papers/p263-fisher.pdf" "Very-Long-Instruction-Word-Architectures-and-the.pdf"
dl "https://people.eecs.berkeley.edu/~kubitron/courses/cs252-F00/handouts/papers/p231-smith.pdf" "Decoupled-Access-Execute-Computer-Architectures.pdf"
dl "https://homepages.inf.ed.ac.uk/npt/pubs/ics-93.pdf" "The-Effectiveness-of-Decoupling.pdf"
dl "https://www.eecs.harvard.edu/~htk/publication/1982-kung-why-systolic-architecture.pdf" "Why-Systolic-Architectures.pdf"
dl "https://www.cs.auckland.ac.nz/courses/compsci703s1c/resources/Bouknight-ILIAC-IV.pdf" "The-ILLIAC-IV-System.pdf"
dl "http://cva.stanford.edu/classes/cs99s/papers/hillis-steele-data-parallel-algorithms.pdf" "Data-Parallel-Algorithms.pdf"
dl "http://www.ai.mit.edu/projects/aries/course/notes/tera.pdf" "The-Tera-Computer-System.pdf"
dl "https://groups.csail.mit.edu/cag/raw/documents/Waingold-Computer-1997.pdf" "Baring-It-All-to-Software-Raw-Machines.pdf"
dl "https://www.cs.utexas.edu/~mckinley/papers/trips-computer-2004.pdf" "Scaling-to-the-End-of-Silicon-with-EDGE-Architec.pdf"
dl "https://cseweb.ucsd.edu/~swanson/papers/Micro2003WaveScalar.pdf" "WaveScalar.pdf"
dl "http://www.cs.ucr.edu/~kmiller/references/hauser97garp.pdf" "Garp-A-MIPS-Processor-with-a-Reconfigurable-Copr.pdf"
dl "http://www.cs.cmu.edu/~seth/papers/goldstein-ieee00.pdf" "PipeRench-A-Reconfigurable-Architecture-and-Comp.pdf"
echo "done -> $OUT/"
