#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://people.cs.rutgers.edu/~uli/cs516/spring2020/readings/PracticalDependenceTesting-PLDI1991.pdf" "Practical-Dependence-Testing.pdf"
dl "http://www.cs.umd.edu/~pugh/papers/omega.pdf" "The-Omega-Test-a-Fast-and-Practical-Integer-Prog.pdf"
dl "https://suif.stanford.edu/papers/wolf91b.pdf" "A-Loop-Transformation-Theory-and-an-Algorithm-to.pdf"
dl "https://suif.stanford.edu/papers/wolf91a.pdf" "A-Data-Locality-Optimizing-Algorithm.pdf"
dl "https://www.cs.utexas.edu/~mckinley/papers/asplos-1994.pdf" "Compiler-Optimizations-for-Improving-Data-Locali.pdf"
dl "https://www.cs.utexas.edu/~mckinley/papers/lcpc-1993.pdf" "Maximizing-Loop-Parallelism-and-Improving-Data-L.pdf"
dl "https://suif.stanford.edu/papers/lam-asplos91.pdf" "The-Cache-Performance-and-Optimizations-of-Block.pdf"
dl "http://rsim.cs.uiuc.edu/arch/qual_papers/compilers/allen87.pdf" "Automatic-Translation-of-FORTRAN-Programs-to-Vec.pdf"
dl "https://groups.csail.mit.edu/cag/slp/SLP-PLDI-2000.pdf" "Exploiting-Superword-Level-Parallelism-with-Mult.pdf"
dl "https://www.ece.lsu.edu/jxr/Publications-pdf/pldi08.pdf" "A-Practical-Automatic-Polyhedral-Parallelizer-an.pdf"
dl "https://inria.hal.science/inria-00551087/file/BPCB10-CC.pdf" "The-Polyhedral-Model-Is-More-Widely-Applicable-T.pdf"
dl "https://perso.ens-lyon.fr/christophe.alias/impact2011/impact-07.pdf" "Polly-Polyhedral-Optimization-in-LLVM.pdf"
dl "https://suif.stanford.edu/papers/lim98.pdf" "Maximizing-Parallelism-and-Minimizing-Synchroniz.pdf"
dl "https://www.csd.uwo.ca/~mmorenom/CS433-CS9624/Resources/Scheduling_multithreaded_computations_by_work_stealing.pdf" "Scheduling-Multithreaded-Computations-by-Work-St.pdf"
dl "https://pages.cs.wisc.edu/~markhill/restricted/pldi98_cilk.pdf" "The-Implementation-of-the-Cilk-5-Multithreaded-L.pdf"
dl "https://ftp.cs.wisc.edu/sohi/papers/1995/isca.multiscalar.pdf" "Multiscalar-Processors.pdf"
dl "https://www.cs.cmu.edu/~zhaia/publications/tlds_isca00.pdf" "A-Scalable-Approach-to-Thread-Level-Speculation.pdf"
echo "done -> $OUT/"
