#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://arxiv.org/pdf/1312.6114" "Auto-Encoding-Variational-Bayes-VAE.pdf"
dl "https://arxiv.org/pdf/1406.2661" "Generative-Adversarial-Nets-GAN.pdf"
dl "https://arxiv.org/pdf/2006.11239" "Denoising-Diffusion-Probabilistic-Models-DDPM.pdf"
echo "done -> $OUT/"
