#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://haoxintu.github.io/files/1-A%20Unified%20Approach%20to%20Global%20Program%20Optimization.pdf" "A-Unified-Approach-to-Global-Program-Optimizatio.pdf"
dl "https://www.cs.utexas.edu/~pingali/CS380C/2010/papers/ssaCytron.pdf" "Efficiently-Computing-Static-Single-Assignment-F.pdf"
dl "https://www.oracle.com/technetwork/java/javase/tech/c2-ir95-150110.pdf" "A-Simple-Graph-Based-Intermediate-Representation.pdf"
echo "done -> $OUT/"
