#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://web.eecs.umich.edu/~mahlke/courses/583f12/reading/chaitin82.pdf" "Register-Allocation-and-Spilling-via-Graph-Color.pdf"
dl "https://www.cse.iitm.ac.in/~krishna/cs6013/george.pdf" "Iterated-Register-Coalescing.pdf"
dl "https://web.cs.ucla.edu/~palsberg/course/cs132/linearscan.pdf" "Linear-Scan-Register-Allocation.pdf"
dl "https://people.eecs.berkeley.edu/~kubitron/courses/cs252-S12/handouts/papers/TraceScheduling.pdf" "Trace-Scheduling-A-Technique-for-Global-Microcod.pdf"
dl "https://www.cs.cmu.edu/afs/cs/academic/class/15740-f18/www/papers/pldi88-lam-softwarepipelining.pdf" "Software-Pipelining-An-Effective-Scheduling-Tech.pdf"
echo "done -> $OUT/"
