#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "https://web.eecs.umich.edu/~mahlke/courses/583f12/reading/chaitin82.pdf" "Register-Allocation-Spilling-via-Graph-Coloring.pdf"
dl "https://www.cse.iitm.ac.in/~krishna/cs6013/george.pdf" "Iterated-Register-Coalescing.pdf"
dl "http://web.cs.ucla.edu/~palsberg/course/cs132/linearscan.pdf" "Linear-Scan-Register-Allocation.pdf"
dl "https://people.eecs.berkeley.edu/~kubitron/courses/cs252-S12/handouts/papers/TraceScheduling.pdf" "Trace-Scheduling.pdf"
dl "https://suif.stanford.edu/papers/lam-sp.pdf" "Software-Pipelining-An-Effective-Scheduling-Tech.pdf"
dl "http://www.cs.ucla.edu/~palsberg/paper/aplas05.pdf" "Register-Allocation-via-Coloring-of-Chordal-Grap.pdf"
dl "https://compilers.cs.uni-saarland.de/papers/ssara.pdf" "Register-Allocation-for-Programs-in-SSA-Form.pdf"
dl "http://www.cs.ucla.edu/~palsberg/paper/PereiraPalsberg08.pdf" "Register-Allocation-by-Puzzle-Solving.pdf"
echo "done -> $OUT/"
