#!/usr/bin/env bash
# Auto-generated by lib/gen-guide.py. Downloads the open PDFs for this list.
set -uo pipefail
cd "$(dirname "$0")"
OUT=pdfs; mkdir -p "$OUT"
UA='Mozilla/5.0'
dl(){ local u="$1" f="$OUT/$2"; if curl -fsSL -A "$UA" -o "$f" "$u" && [ "$(head -c4 "$f")" = "%PDF" ]; then echo "ok   $2"; else echo "FAIL $2"; rm -f "$f"; fi; }
dl "http://rsim.cs.uiuc.edu/arch/qual_papers/compilers/knoop92.pdf" "Lazy-Code-Motion.pdf"
dl "https://groups.csail.mit.edu/cag/slp/SLP-PLDI-2000.pdf" "Exploiting-Superword-Level-Parallelism-with-Mult.pdf"
echo "done -> $OUT/"
